### ISSUE TITLE
Important!

### ISSUE THREAD

**Issue by Tooconfident** [tomtaborsky/TeaCozy#5]
https://github.com/tomtaborsky/TeaCozy/blob/master/resources/css/index.css#L79-L83

This css overall is great here. `width: inherit`, and `align-items: center;` might not actually be doing anything at the moment. removing those and keeping the rest will simplify your code and keep your same style choice.

**Comment by tomtaborsky** [comment]
Thank you for all your reviews, I will incorporate those as necessary :)
